### ISSUE TITLE
Retrieve quotes by a given tag

### ISSUE THREAD

**Issue by GalaxySH** [tronalddump-io/tronald-app#6]
It's me again. Thanks for fixing the last issue for the get quotes by tag option, but now there's another issue.
When requesting a quote by a certain tag (e.g. Hillary Clinton) all you get back is a link to the site for the quote, I don't know if this was intended or it's supposed to return a quote, but either way, it isn't what the docs say should be returned. Getting nothing but a link back to the home site kind of defeats the purpose of the API (for my purposes anyway).
Thanks.
*PS: feature idea: no case sensitivity?*
![image](https://user-images.githubusercontent.com/34115400/71649009-bafa3180-2cd0-11ea-9ff5-b21584377843.png)

**Comment by matchilling** [comment]
Hi @GalaxySH, thanks for raising the issue. [I've added](https://github.com/tronalddump-io/tronald-app/commit/ceb6ca4a6fc5bb8f268810dc4680fa9904d7d856) the described search functionality to the search endpoint. You can now retrieve quotes by a given tag as follows:

```shell
curl --request GET \
  'https://www.tronalddump.io/search/quote?tag=Jeb%20Bush' \
  --header 'Accept: application/hal+json'
```

Due to the underlying data structure it is unfortunately not possible to introduce case insensitivity feature without breaking backward compatibility.

_Please be aware that the api documentation hasn't been update yet and does not include the new functionality as described above. You can follow the progress on this issue [here](https://github.com/tronalddump-io/tronald-app/issues/7) and use the [Postman collection](https://github.com/tronalddump-io/tronald-app/blob/master/postman/io.tronalddump.postman_collection.json) as an additional reference._

Thank you for your contribution 🙏
