### ISSUE TITLE
Allow case insensitive search

### ISSUE THREAD

**Issue by nkoehring** [tronalddump-io/tronald-app#8]
The website allows to search but only finds exact matches. Some simple stemming would be very useful to make searchers life easier.

**Comment by matchilling** [comment]
Hej hej @nkoehring 👋 ,

Thanks for your contribution. The [latest release](https://github.com/tronalddump-io/tronald-app/commit/b8cb0a6902c54932b272624db6c2c8133943bbdd) includes a feature to allow queries being case insensitive.

Have a try with it and let me know if it helps, otherwise please share more details on your current use case.

Bests, M
